COMMIT;

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_meal_logs_user_id ON meal_logs (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_workout_logs_user_id ON workout_logs (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_weight_logs_user_id ON weight_logs (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_nodes_user_id ON nodes (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_goals_user_id ON goals (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_focus_items_user_id ON focus_items (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_backburner_user_id ON backburner (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_milestones_user_id ON milestones (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_highlights_user_id ON highlights (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_habits_user_id ON habits (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_habit_logs_user_id ON habit_logs (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_eulogies_user_id ON eulogies (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pomodoro_logs_user_id ON pomodoro_logs (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_subtasks_user_id ON subtasks (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_mood_logs_user_id ON mood_logs (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_supplements_user_id ON supplements (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_supplement_logs_user_id ON supplement_logs (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_workout_goals_user_id ON workout_goals (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_workout_performance_user_id ON workout_performance (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_io_logs_user_id ON io_logs (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_curriculum_chapters_user_id ON curriculum_chapters (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_curriculum_topics_user_id ON curriculum_topics (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ritual_items_user_id ON ritual_items (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ritual_logs_user_id ON ritual_logs (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_daily_tasks_user_id ON daily_tasks (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_curriculum_categories_user_id ON curriculum_categories (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_curricula_user_id ON curricula (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_curriculum_resources_user_id ON curriculum_resources (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_media_log_user_id ON media_log (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_custom_foods_user_id ON custom_foods (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_workout_plans_user_id ON workout_plans (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_plan_exercises_user_id ON plan_exercises (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_weekly_reports_user_id ON weekly_reports (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_custom_recipes_user_id ON custom_recipes (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sleep_logs_user_id ON sleep_logs (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_water_logs_user_id ON water_logs (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_user_settings_user_id ON user_settings (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_hardware_opportunities_user_id ON hardware_opportunities (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_day_plan_blocks_user_id ON day_plan_blocks (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_tasks_user_id ON tasks (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_wins_user_id ON wins (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_contacts_user_id ON contacts (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_nudges_user_id ON nudges (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_focus_sessions_user_id ON focus_sessions (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_calendar_events_user_id ON calendar_events (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_calendar_backups_user_id ON calendar_backups (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_mini_games_user_id ON mini_games (user_id);

-- Extra table noticed in syncManager:
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_recurring_task_templates_user_id ON recurring_task_templates (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_morning_briefs_user_id ON morning_briefs (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_outreach_targets_user_id ON outreach_targets (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_practice_scores_user_id ON practice_scores (user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_task_estimate_cal_user_id ON task_estimate_calibration (user_id);

-- Composite indexes for time-series data
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_meal_logs_user_date ON meal_logs (user_id, log_date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_workout_logs_user_date ON workout_logs (user_id, log_date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_weight_logs_user_date ON weight_logs (user_id, log_date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_mood_logs_user_date ON mood_logs (user_id, log_date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_supplement_logs_user_date ON supplement_logs (user_id, log_date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_habit_logs_user_date ON habit_logs (user_id, date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pomodoro_logs_user_date ON pomodoro_logs (user_id, date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_io_logs_user_date ON io_logs (user_id, date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ritual_logs_user_date ON ritual_logs (user_id, date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_daily_tasks_user_date ON daily_tasks (user_id, date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sleep_logs_user_date ON sleep_logs (user_id, log_date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_water_logs_user_date ON water_logs (user_id, log_date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_day_plan_blocks_user_date ON day_plan_blocks (user_id, log_date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_wins_user_date ON wins (user_id, log_date);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_calendar_events_user_time ON calendar_events (user_id, start_time);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_tasks_user_deadline ON tasks (user_id, deadline);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_goals_user_deadline ON goals (user_id, deadline);
